from accounts.views.authorize import *
from accounts.views.confirm import *
from accounts.views.delete import *
from accounts.views.index import *
from accounts.views.link import *
from accounts.views.link_form import *
from accounts.views.login import *
from accounts.views.logout import *
from accounts.views.server_form import *
from accounts.views.servers import *
from accounts.views.sync import *
from accounts.views.sync_form import *
