# Generated by Django 3.1.5 on 2021-01-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlexAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TraktAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64)),
                ('token_type', models.CharField(max_length=32)),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=32, null=True)),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TraktAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.traktauth')),
                ('plex_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.plexaccount')),
            ],
        ),
    ]
