# Generated by Django 3.1.5 on 2021-01-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(max_length=128)),
                ('sync_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plexaccount',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.plexserver'),
        ),
    ]
