# Generated by Django 3.1.5 on 2021-01-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plexaccount',
            name='server',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
