version: '2'

services:
  rabbitmq:
    image: rabbitmq:latest

  plaxt:
    image: dbutrimov/plaxt:latest
    environment:
      - ENV_PATH=/config/.env
    volumes:
      - ~/.config/plaxt:/config
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
